DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS friendship CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS mpa CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS film_genres CASCADE;

CREATE TABLE IF NOT EXISTS users(
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(254) NOT NULL,
    login    VARCHAR NOT NULL,
    name     VARCHAR NOT NULL,
    birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS friendship(
   PRIMARY KEY(user_id, friend_id),
   user_id   BIGINT NOT NULL,
   friend_id BIGINT NOT NULL,
   FOREIGN KEY(user_id) REFERENCES users(user_id),
   FOREIGN KEY(friend_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS mpa(
   rating_id INT AUTO_INCREMENT PRIMARY KEY,
   name      VARCHAR
);

CREATE TABLE IF NOT EXISTS films(
   film_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name        VARCHAR NOT NULL,
   description VARCHAR(200) NOT NULL,
   release_date DATE NOT NULL,
   duration    INT,
   rating_id   INT
);

CREATE TABLE IF NOT EXISTS likes(
   film_id BIGINT,
   user_id BIGINT,
   PRIMARY KEY(user_id, film_id),
   FOREIGN KEY(film_id) REFERENCES films(film_id),
   FOREIGN KEY(user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS genres(
   genre_id INT AUTO_INCREMENT PRIMARY KEY,
   name     VARCHAR
);

CREATE TABLE IF NOT EXISTS film_genres(
   PRIMARY KEY(film_id, genre_id),
   film_id  INT,
   genre_id INT,
   FOREIGN KEY(film_id) REFERENCES films(film_id),
   FOREIGN KEY(genre_id) REFERENCES genres(genre_id)
);






